config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {registrations: 'registrations'}

  get '/profile/:id', to: 'users#show', as: :profile

  authenticated :user do
    root to: "dashboards#index", as: :dashboard
  end

  resources :thoughts, except: [:index] do
    resources :votes, only: [:create, :destroy], module: :thoughts
  end

  root 'landing_page#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/votable.rb
module Votable
  extend ActiveSupport::Concern

  def upvote(votable)
    votes.create(votable: votable, user_id: self.id, up: true)
  end

  def downvote(votable)
    votes.create(votable: votable, user_id: self.id, down: true)
  end

  def voted?(votable)
    find_vote(votable).exists?
  end

  def upvoted_resources
    Vote.where(user_id: self.id, up: true)
  end

  def all_voted
    Vote.where(user_id: self.id).map(&:votable_id)
  end

  def downvoted_resources
    Vote.where(user_id: self.id, down: true)
  end

  private

  def find_vote(votable)
    Vote.where(votable_id: votable.id, user_id: self.id)
  end
end

app/models/thought.rb
class Thought < ApplicationRecord
  belongs_to :user
  has_many :votes, as: :votable

  validates :body, presence: true, length: {maximum: 500}

  delegate :username, to: :user

end

app/models/user.rb
class User < ApplicationRecord
  include Votable

  has_many :thoughts
  has_many :votes, dependent: :destroy
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def username
    @username ||= email.split('@')[0]
  end

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :votable, polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  def index
    thoughts = Thought.where.not(id: current_user.all_voted)
    @thought = thoughts.sample
    @suggestions = SuggestionsService.new(current_user).call
  end
end

app/controllers/landing_page_controller.rb
class LandingPageController < ApplicationController
  skip_before_action :authenticate_user!
  def index
    @hide_nav = true
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def after_sign_up_path_for(user)
    profile_path(user)
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :account_update, keys: [
        :username, :first_name, :last_name,
        :bio, :email, :password, :password_confirmation
      ]
    )
  end
end

app/controllers/thoughts/likes_controller.rb
class Thoughts::LikesController < LikesController
  before_action :set_votable

  private

  def set_votable
    @votable = Thought.find(params[:thought_id])
  end
end

app/controllers/thoughts/votes_controller.rb
class Thoughts::VotesController < VotesController
  before_action :set_votable

  private

  def set_votable
    @votable = Thought.find(params[:thought_id])
  end
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
  before_action :find_thought, only: [:show, :edit, :update, :destroy]

  def show
  end

  def new
    @thought = Thought.new
    @thought.user = current_user
  end

  def create
    @thought = Thought.create(thought_params)
    @thought.user = current_user
    
    if @thought.save
      flash[:notice] = "Created thought"
      redirect_to @thought
    else
      flash[:alert] = 'cannot create thought'
      render 'new'
    end
  end

  def edit
  end

  def update
    if @thought.update(thought_params)
      flash[:notice] = 'Update thought'
      redirect_to @thought
    else
      flash[:alert] = 'cannot update'
      render 'edit'
    end
  end

  def destroy
    @thought.destroy
    flash[:notice] = 'Deleted thought'
    redirect_to dashboard_path
  end

  private

  def find_thought
    @thought = Thought.find(params[:id])
  end

  def thought_params
    params.require(:thought).permit(:body)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    if params[:upvote]
      current_user.upvote(@votable)
    else
      current_user.downvote(@votable)
    end

    redirect_to dashboard_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/landing_page_helper.rb
module LandingPageHelper
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/views/dashboards/index.html.erb
<section class="dashboard-container">
  <section class="dashboard-side-menu">
    <div class="dashboard-menu-title"><h1><%= current_user.username.upcase %></h1></div>
    <div class="dashboard-menu-sugestions">
      <h2>Sugestions</h2>
      <% @suggestions.each do |most_liked_user| %>
        <p><%= link_to most_liked_user.username, profile_path(most_liked_user) %></p>
      <% end %>
    </div>
  </section>
  <section class="dashboard-body">
    <div class="dashboard-body-card">
      <%= @thought.username %>

      <div class="card">
        <div class="card-content">
          <p class="title">
            <%= @thought.body %>
          </p>
        </div>
        <footer class="card-footer">
          <p class="card-footer-item">
            <span>
              <%= link_to "Like", thought_votes_path(@thought, upvote: :true), method: :post %>
            </span>
          </p>
          <p class="card-footer-item">
            <span>
              <%= link_to "Unlike", thought_votes_path(@thought, dowvote: :true), method: :post %>
            </span>
          </p>
        </footer>
      </div> 

    </div>
  </section>
</section>

app/views/landing_page/index.html.erb
<section class="landing-page">
  <section class="landing-page-box">
    <h1 class='title'>Affinity</h1>
    <p><%= link_to "Sign up", new_user_registration_path, class: 'button is-primary is-rounded' %></p>
    <p>or</p>
    <p><%= link_to "Sign in", new_user_session_path, class: 'button is-primary is-rounded' %></p>
  </section>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Affinity</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.8.0/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
  </head>

  <body>
  <%= render 'layouts/shared/navbar' unless @hide_nav %>
  <% flash.each do |key, msg| %>
    <p class="#{key}"><%= msg %></p>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/shared/_navbar.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
  <div class="navbar-brand">
    <%= link_to "Affinity", root_path, class: 'navbar-item' %>

    <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
      <span aria-hidden="true"></span>
    </a>
  </div>

  <div id="navbarBasicExample" class="navbar-menu">

    <div class="navbar-end">
      <% if user_signed_in? %>
      <div class="navbar-item has-dropdown is-hoverable">
        <a class="navbar-link">
          More
        </a>
        <div class="navbar-dropdown">
          <%= link_to "Main", root_path, class: 'navbar-item' %>
          <%= link_to "New Thought", new_thought_path, class: 'navbar-item' %>
          <%= link_to "Profile", profile_path(current_user), class: 'navbar-item' %>
          <%= link_to "Edit Profile", edit_user_registration_path, class: 'navbar-item' %>
        </div>
      </div>
      <div class="navbar-item">
        <div class="buttons">
            <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'button' %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, class: 'button' %>
            <%= link_to "Sign in", new_user_session_path, class: 'button' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</nav>

app/views/thoughts/_form.html.erb
<%= form_for(@thought) do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit "Create thought" %>
<% end %>

app/views/thoughts/edit.html.erb
<%= render 'form' %>

app/views/thoughts/index.html.erb
<%# <%= @thoughts.body %1> %>

app/views/thoughts/new.html.erb
<%= form_for(@thought) do |f| %>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <%= f.submit "Create thought" %>
<% end %>

app/views/thoughts/show.html.erb
<%= @thought.body %>
<%= link_to "Edit Thought", edit_thought_path(@thought) if current_user.id == @thought.user_id %>
<%= link_to "Delete thought", thought_path(@thought), method: :delete if current_user == @thought.user %>

app/views/users/show.html.erb
<section class="profile-container">
  <section class="profile-info">
    <p><%= @user.username %></p>
  </section>

  <section class="profile-follows">
    <p>total followers: 0</p>
    <p>total following: 0</p>
  </section>

  <section class="profile_thoughts-container">
    <section class="profile_thoughts">
      <% @user.thoughts.each do |t| %>
        <p><%= t.body %></p>
      <% end %>
    </section>
  </section>

</section>